spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.entity
  mapperLocations: com/mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/do?serverTimezone=GMT%2B8
    username: root
    password: wmn6356308
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /views/
      suffix: .jsp